# Generated by Django 4.2.5 on 2023-09-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default="Value"),
            preserve_default=False,
        ),
    ]
